/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsIndexRouteImport } from "./routes/settings.index";
import { Route as SettingsUxRouteImport } from "./routes/settings.ux";
import { Route as SettingsClientApiRouteImport } from "./routes/settings.client-api";
import { Route as AuthRecentlyTrashedRouteImport } from "./routes/_auth/recently-trashed";
import { Route as AuthRecentlyInboxedRouteImport } from "./routes/_auth/recently-inboxed";
import { Route as AuthRecentlyArchivedRouteImport } from "./routes/_auth/recently-archived";
import { Route as AuthRandomInboxRouteImport } from "./routes/_auth/random-inbox";
import { Route as AuthPagesRouteImport } from "./routes/_auth/pages";
import { Route as AuthHistoryRouteImport } from "./routes/_auth/history";
import { Route as AuthPagesIndexRouteImport } from "./routes/_auth/pages.index";
import { Route as AuthPagesPageIdRouteImport } from "./routes/_auth/pages.$pageId";
import { Route as AuthFileFileIdRouteImport } from "./routes/_auth/file.$fileId";

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsUxRoute = SettingsUxRouteImport.update({
  id: "/ux",
  path: "/ux",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsClientApiRoute = SettingsClientApiRouteImport.update({
  id: "/client-api",
  path: "/client-api",
  getParentRoute: () => SettingsRoute,
} as any);
const AuthRecentlyTrashedRoute = AuthRecentlyTrashedRouteImport.update({
  id: "/recently-trashed",
  path: "/recently-trashed",
  getParentRoute: () => AuthRoute,
} as any);
const AuthRecentlyInboxedRoute = AuthRecentlyInboxedRouteImport.update({
  id: "/recently-inboxed",
  path: "/recently-inboxed",
  getParentRoute: () => AuthRoute,
} as any);
const AuthRecentlyArchivedRoute = AuthRecentlyArchivedRouteImport.update({
  id: "/recently-archived",
  path: "/recently-archived",
  getParentRoute: () => AuthRoute,
} as any);
const AuthRandomInboxRoute = AuthRandomInboxRouteImport.update({
  id: "/random-inbox",
  path: "/random-inbox",
  getParentRoute: () => AuthRoute,
} as any);
const AuthPagesRoute = AuthPagesRouteImport.update({
  id: "/pages",
  path: "/pages",
  getParentRoute: () => AuthRoute,
} as any);
const AuthHistoryRoute = AuthHistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => AuthRoute,
} as any);
const AuthPagesIndexRoute = AuthPagesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthPagesRoute,
} as any);
const AuthPagesPageIdRoute = AuthPagesPageIdRouteImport.update({
  id: "/$pageId",
  path: "/$pageId",
  getParentRoute: () => AuthPagesRoute,
} as any);
const AuthFileFileIdRoute = AuthFileFileIdRouteImport.update({
  id: "/file/$fileId",
  path: "/file/$fileId",
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRouteWithChildren;
  "/history": typeof AuthHistoryRoute;
  "/pages": typeof AuthPagesRouteWithChildren;
  "/random-inbox": typeof AuthRandomInboxRoute;
  "/recently-archived": typeof AuthRecentlyArchivedRoute;
  "/recently-inboxed": typeof AuthRecentlyInboxedRoute;
  "/recently-trashed": typeof AuthRecentlyTrashedRoute;
  "/settings/client-api": typeof SettingsClientApiRoute;
  "/settings/ux": typeof SettingsUxRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/file/$fileId": typeof AuthFileFileIdRoute;
  "/pages/$pageId": typeof AuthPagesPageIdRoute;
  "/pages/": typeof AuthPagesIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/history": typeof AuthHistoryRoute;
  "/random-inbox": typeof AuthRandomInboxRoute;
  "/recently-archived": typeof AuthRecentlyArchivedRoute;
  "/recently-inboxed": typeof AuthRecentlyInboxedRoute;
  "/recently-trashed": typeof AuthRecentlyTrashedRoute;
  "/settings/client-api": typeof SettingsClientApiRoute;
  "/settings/ux": typeof SettingsUxRoute;
  "/settings": typeof SettingsIndexRoute;
  "/file/$fileId": typeof AuthFileFileIdRoute;
  "/pages/$pageId": typeof AuthPagesPageIdRoute;
  "/pages": typeof AuthPagesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/settings": typeof SettingsRouteWithChildren;
  "/_auth/history": typeof AuthHistoryRoute;
  "/_auth/pages": typeof AuthPagesRouteWithChildren;
  "/_auth/random-inbox": typeof AuthRandomInboxRoute;
  "/_auth/recently-archived": typeof AuthRecentlyArchivedRoute;
  "/_auth/recently-inboxed": typeof AuthRecentlyInboxedRoute;
  "/_auth/recently-trashed": typeof AuthRecentlyTrashedRoute;
  "/settings/client-api": typeof SettingsClientApiRoute;
  "/settings/ux": typeof SettingsUxRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/_auth/file/$fileId": typeof AuthFileFileIdRoute;
  "/_auth/pages/$pageId": typeof AuthPagesPageIdRoute;
  "/_auth/pages/": typeof AuthPagesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/settings"
    | "/history"
    | "/pages"
    | "/random-inbox"
    | "/recently-archived"
    | "/recently-inboxed"
    | "/recently-trashed"
    | "/settings/client-api"
    | "/settings/ux"
    | "/settings/"
    | "/file/$fileId"
    | "/pages/$pageId"
    | "/pages/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/history"
    | "/random-inbox"
    | "/recently-archived"
    | "/recently-inboxed"
    | "/recently-trashed"
    | "/settings/client-api"
    | "/settings/ux"
    | "/settings"
    | "/file/$fileId"
    | "/pages/$pageId"
    | "/pages";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/settings"
    | "/_auth/history"
    | "/_auth/pages"
    | "/_auth/random-inbox"
    | "/_auth/recently-archived"
    | "/_auth/recently-inboxed"
    | "/_auth/recently-trashed"
    | "/settings/client-api"
    | "/settings/ux"
    | "/settings/"
    | "/_auth/file/$fileId"
    | "/_auth/pages/$pageId"
    | "/_auth/pages/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  SettingsRoute: typeof SettingsRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/": {
      id: "/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/ux": {
      id: "/settings/ux";
      path: "/ux";
      fullPath: "/settings/ux";
      preLoaderRoute: typeof SettingsUxRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/client-api": {
      id: "/settings/client-api";
      path: "/client-api";
      fullPath: "/settings/client-api";
      preLoaderRoute: typeof SettingsClientApiRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/_auth/recently-trashed": {
      id: "/_auth/recently-trashed";
      path: "/recently-trashed";
      fullPath: "/recently-trashed";
      preLoaderRoute: typeof AuthRecentlyTrashedRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/recently-inboxed": {
      id: "/_auth/recently-inboxed";
      path: "/recently-inboxed";
      fullPath: "/recently-inboxed";
      preLoaderRoute: typeof AuthRecentlyInboxedRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/recently-archived": {
      id: "/_auth/recently-archived";
      path: "/recently-archived";
      fullPath: "/recently-archived";
      preLoaderRoute: typeof AuthRecentlyArchivedRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/random-inbox": {
      id: "/_auth/random-inbox";
      path: "/random-inbox";
      fullPath: "/random-inbox";
      preLoaderRoute: typeof AuthRandomInboxRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/pages": {
      id: "/_auth/pages";
      path: "/pages";
      fullPath: "/pages";
      preLoaderRoute: typeof AuthPagesRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/history": {
      id: "/_auth/history";
      path: "/history";
      fullPath: "/history";
      preLoaderRoute: typeof AuthHistoryRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/pages/": {
      id: "/_auth/pages/";
      path: "/";
      fullPath: "/pages/";
      preLoaderRoute: typeof AuthPagesIndexRouteImport;
      parentRoute: typeof AuthPagesRoute;
    };
    "/_auth/pages/$pageId": {
      id: "/_auth/pages/$pageId";
      path: "/$pageId";
      fullPath: "/pages/$pageId";
      preLoaderRoute: typeof AuthPagesPageIdRouteImport;
      parentRoute: typeof AuthPagesRoute;
    };
    "/_auth/file/$fileId": {
      id: "/_auth/file/$fileId";
      path: "/file/$fileId";
      fullPath: "/file/$fileId";
      preLoaderRoute: typeof AuthFileFileIdRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthPagesRouteChildren {
  AuthPagesPageIdRoute: typeof AuthPagesPageIdRoute;
  AuthPagesIndexRoute: typeof AuthPagesIndexRoute;
}

const AuthPagesRouteChildren: AuthPagesRouteChildren = {
  AuthPagesPageIdRoute: AuthPagesPageIdRoute,
  AuthPagesIndexRoute: AuthPagesIndexRoute,
};

const AuthPagesRouteWithChildren = AuthPagesRoute._addFileChildren(
  AuthPagesRouteChildren,
);

interface AuthRouteChildren {
  AuthHistoryRoute: typeof AuthHistoryRoute;
  AuthPagesRoute: typeof AuthPagesRouteWithChildren;
  AuthRandomInboxRoute: typeof AuthRandomInboxRoute;
  AuthRecentlyArchivedRoute: typeof AuthRecentlyArchivedRoute;
  AuthRecentlyInboxedRoute: typeof AuthRecentlyInboxedRoute;
  AuthRecentlyTrashedRoute: typeof AuthRecentlyTrashedRoute;
  AuthFileFileIdRoute: typeof AuthFileFileIdRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthHistoryRoute: AuthHistoryRoute,
  AuthPagesRoute: AuthPagesRouteWithChildren,
  AuthRandomInboxRoute: AuthRandomInboxRoute,
  AuthRecentlyArchivedRoute: AuthRecentlyArchivedRoute,
  AuthRecentlyInboxedRoute: AuthRecentlyInboxedRoute,
  AuthRecentlyTrashedRoute: AuthRecentlyTrashedRoute,
  AuthFileFileIdRoute: AuthFileFileIdRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface SettingsRouteChildren {
  SettingsClientApiRoute: typeof SettingsClientApiRoute;
  SettingsUxRoute: typeof SettingsUxRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsClientApiRoute: SettingsClientApiRoute,
  SettingsUxRoute: SettingsUxRoute,
  SettingsIndexRoute: SettingsIndexRoute,
};

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
