/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsAccountRouteImport } from "./routes/settings.account";
import { Route as AuthHelloWorldRouteImport } from "./routes/_auth/hello-world";

const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: "/settings/account",
  path: "/settings/account",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthHelloWorldRoute = AuthHelloWorldRouteImport.update({
  id: "/hello-world",
  path: "/hello-world",
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/hello-world": typeof AuthHelloWorldRoute;
  "/settings/account": typeof SettingsAccountRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/hello-world": typeof AuthHelloWorldRoute;
  "/settings/account": typeof SettingsAccountRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/_auth/hello-world": typeof AuthHelloWorldRoute;
  "/settings/account": typeof SettingsAccountRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/hello-world" | "/settings/account";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/hello-world" | "/settings/account";
  id: "__root__" | "/" | "/_auth" | "/_auth/hello-world" | "/settings/account";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
  SettingsAccountRoute: typeof SettingsAccountRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/account": {
      id: "/settings/account";
      path: "/settings/account";
      fullPath: "/settings/account";
      preLoaderRoute: typeof SettingsAccountRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/hello-world": {
      id: "/_auth/hello-world";
      path: "/hello-world";
      fullPath: "/hello-world";
      preLoaderRoute: typeof AuthHelloWorldRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthHelloWorldRoute: typeof AuthHelloWorldRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthHelloWorldRoute: AuthHelloWorldRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SettingsAccountRoute: SettingsAccountRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
